server:
  port: 9393
management:
  contextPath: /management
  security:
    enabled: false
info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"
spring:
  application:
    name: dataflow
  cloud:
    config:
      uri: http://localhost:8888
    deployer:
      cloudfoundry:
        task:
          apiTimeout: 360
        stream:
          apiTimeout: 360
    dataflow:
      security:
        cf-use-uaa: true

#
# If you prefer to use Eureka to locate the Config Server, you can do that by setting
# spring.cloud.config.discovery.enabled=true (default "false"). The net result of that is 
# that client apps all need a bootstrap.yml (or an environment variable) with the Eureka 
# server address, e.g. in eureka.client.serviceUrl.defaultZone
#
#  cloud:
#     config:
#        discovery:
#           enabled: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
